PWD directory

diff --git a/.github/workflows/regression-test.yaml b/.github/workflows/regression-test.yaml
--- a/.github/workflows/regression-test.yaml
+++ b/.github/workflows/regression-test.yaml
@@ -47,13 +47,15 @@ jobs:
           source ~/.bashrc
 
       - name: Navigate to script directory
-        run: cd $HOME/utils/scripts
-
-      - name: Run code formatting check
         run: |
+          cd $GITHUB_WORKSPACE
           pwd
-          chmod +x $HOME/utils/scripts/code-format/format_modified.sh
-          if ! $HOME/utils/scripts/code-format/format_modified.sh -g -ca; then
-            echo "Code format check failed. Please fix the formatting issues by running the following script: /utils/scripts/format_modified.sh"
-            exit 1 
-          fi
+
+      # - name: Run code formatting check
+      #   run: |
+      #     pwd
+      #     chmod +x $GITHUB_WORKSPACE/utils/scripts/code-format/format_modified.sh
+      #     if ! $GITHUB_WORKSPACE/utils/scripts/code-format/format_modified.sh -g -ca; then
+      #       echo "Code format check failed. Please fix the formatting issues by running the following script: /utils/scripts/format_modified.sh"
+      #       exit 1 
+      #     fi
