Update format check.

diff --git a/.github/workflows/regression-test.yaml b/.github/workflows/regression-test.yaml
--- a/.github/workflows/regression-test.yaml
+++ b/.github/workflows/regression-test.yaml
@@ -57,10 +57,10 @@ jobs:
           . ~/.bashrc
       - name: Run code formatting check
         run: |
-          cd utils/scripts/actions-pipeline/code-format
+          cd $GITHUB_WORKSPACE/utils/scripts/actions-pipeline/code-format
           chmod +x format_modified.sh
           if ! ./format_modified.sh -g -ca; then
-            echo "Code format check failed. Please fix the formatting issues by running the following script: /utils/scripts/format_modified.sh"
-            exit 1 
+              echo "Code format check failed. Please fix the formatting issues by running the following script: /utils/scripts/format_modified.sh"
+              exit 1 
           fi
 
