Update format check.

diff --git a/.github/workflows/regression-test.yaml b/.github/workflows/regression-test.yaml
--- a/.github/workflows/regression-test.yaml
+++ b/.github/workflows/regression-test.yaml
@@ -58,5 +58,13 @@ jobs:
       - name: Run code formatting check
         run: |
           cd utils/scripts/actions-pipeline/code-format
-          ls
+          chmod +x format_modified.sh
+          if [ -n "$(git rev-parse --show-toplevel 2>/dev/null)" ]; then
+            if ! ./format_modified.sh -g -ca; then
+              echo "Code format check failed. Please fix the formatting issues by running the following script: /utils/scripts/format_modified.sh"
+              exit 1 
+            fi
+          else
+            echo "Not in a Git repository. Skipping code formatting check."
+          fi
 
